'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class atlasEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=atlasEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property BlogKathgoriesTable() As DbSet(Of BlogKathgoriesTable)
    Public Overridable Property BlogPostKathgoriaTable() As DbSet(Of BlogPostKathgoriaTable)
    Public Overridable Property BlogPostsTable() As DbSet(Of BlogPostsTable)
    Public Overridable Property BlogYpokathgoriesTable() As DbSet(Of BlogYpokathgoriesTable)
    Public Overridable Property AspNetRoles() As DbSet(Of AspNetRoles)
    Public Overridable Property AspNetUserClaims() As DbSet(Of AspNetUserClaims)
    Public Overridable Property AspNetUserLogins() As DbSet(Of AspNetUserLogins)
    Public Overridable Property AspNetUsers() As DbSet(Of AspNetUsers)
    Public Overridable Property BlogProgramma() As DbSet(Of BlogProgramma)
    Public Overridable Property BlogPostKathgoriaTable2() As DbSet(Of BlogPostKathgoriaTable2)

End Class
