'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class temprankingsgroups
    Public Property teamid As Integer
    Public Property bathmoi As Integer
    Public Property teampoints As Integer
    Public Property teambathmoi As Integer
    Public Property teampointsdef As Nullable(Of Integer)
    Public Property teampointsdif As Nullable(Of Integer)
    Public Property teamtotaloff As Nullable(Of Integer)
    Public Property teamtotaldf As Nullable(Of Integer)
    Public Property teamtotaldif As Nullable(Of Integer)

End Class
