'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UserLogins
    Public Property Id As Integer
    Public Property Userid As String
    Public Property Sessionid As String
    Public Property Loggedin As Boolean
    Public Property Datetimelog As Date
    Public Property Usercompname As String
    Public Property Userip As String

End Class
